name: smart_security_combined_prototype
description: "Camera + Fraud Link Detector Prototype"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2   # keep your current Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  # Camera + ML Kit face detection
  camera: ^0.10.0+4
  google_mlkit_face_detection: ^0.3.0
  path_provider: ^2.0.15
  url_launcher: ^6.3.1 

  # Local storage for link history
  shared_preferences: ^2.1.1

  # (Optional) Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
